### ISSUE TITLE
Serverless - TypeError: mod.require is not a function

### ISSUE THREAD

**Issue by oakleaf** [greggman/unzipit#26]
Hello and thank you for an awesome project!

Im trying to use this in my serverless Lambda node18 (es2020) function, and are getting subject mentioned error. Here's the full error:

`
ERROR   Uncaught Exception      {"errorType":"TypeError","errorMessage":"mod.require is not a function","stack":["TypeError: mod.require is not a function","    at dynamicRequire (/var/task/index.js:464:20)","    at /var/task/index.js:468:39","    at /var/task/index.js:526:8","    at /var/task/index.js:32:71","    at node_modules/unzipit/dist/unzipit.js
`

Here's some code:
```
import * as unzipit from 'unzipit';
const { entries } = await unzipit.unzip("https://greggman.github.io/unzipit/test/data/large.zip");
```
Any idea what I am doing wrong?

**Comment by greggman** [comment]
random ideas.

* You can't use `await` outside of an async function (maybe there is some flag for node) that enables that?
* You can't use `import` from a non-module (add "type": "module" to your package.json or include with `require`?

I just tried it on codesandbox.io and it seemed to work

https://codesandbox.io/s/unzipiit-in-node18-r43jbn

**Comment by greggman** [comment]
here's a non-module version

https://codesandbox.io/s/unzipiit-in-node18-non-module-u4l9ew

**Comment by oakleaf** [comment]
Thank you for your unreasonable quick response 😎

Actually, I do use async properly, module setting (with ts). This is the full code:
```
import { Context, APIGatewayEvent } from 'aws-lambda';
import * as unzipit from 'unzipit';

const application = async (event: APIGatewayEvent, context: Context) => { 
const { entries } = await unzipit.unzip("https://greggman.github.io/unzipit/test/data/large.zip");
};
```

And no matter what I do, I always get the same error from the console.

My package.json:
```
{
    "name": "",
    "type": "module",
    "version": "1.0.0",
    "description": "",
    "main": "app.js",
    "author": "Oakleaf",
    "license": "MIT",
    "dependencies": {
        "@lumigo/tracer": "^1.71.2",
        "lambda-multipart-parser": "^1.0.1",
        "mysql2": "^2.3.3",
        "unzipit": "^1.4.0",
        "uuid": "^8.3.2"
    },
    "devDependencies": {
        "@types/aws-lambda": "^8.10.51",
        "@types/node": "^17.0.13",
        "@types/uuid": "^9.0.0",
        "@typescript-eslint/eslint-plugin": "^5.10.2",
        "@typescript-eslint/parser": "^5.10.2",
        "esbuild": "^0.14.14",
        "eslint": "^8.8.0",
        "typescript": "^4"
    }
}
```

Any idea?

**Comment by greggman** [comment]
can you try version v1.4.1 ?

**Comment by Youyou23** [comment]
Hi & thanks for your reply, 

I am running currently into the same problem, 
however, when switching to v1.4.1, the error seems to change to something related to the 'Worker' destructing property, here is the full error i get : 
"TypeError: Cannot destructure property 'Worker' of 'dynamicRequire(...)' as it is undefined.","    at /var/task/index.js:468:27","    at /var/task/index.js:526:8","    at /var/task/index.js:32:71","    at node_modules/unzipit/dist/unzipit.js (/var/task/index.js:33:7)","    at __require (/var/task/index.js:8:50)","    at Object.<anonymous> (/var/task/index.js:4089:23)","    at Module._compile (node:internal/modules/cjs/loader:1159:14)","    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)","    at Module.load (node:internal/modules/cjs/loader:1037:32)","    at Module._load (node:internal/modules/cjs/loader:878:12)"

**Comment by greggman** [comment]
you can try 1.4.2 😆

**Comment by Youyou23** [comment]
Yeah Thanks , it's working ! 
i think It was something related to the distr with 
esbuild ? bc i found a workaround with the v1.4.0 => exclude it from the build, and inject it in my app bundle

**Comment by greggman** [comment]
I think your build is setup in a way that `module.require` no longer exists. It's needed to work with workers in node. I don't know the workaround. I just made it check for `module.require` instead of assuming.

I have no easy way to test locally.
